# Generated by Django 3.1.5 on 2021-01-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub', models.DateField(auto_now_add=True, verbose_name='Date of publication')),
                ('hour', models.TimeField(auto_now_add=True, verbose_name='Time of publication')),
                ('content', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
