# Generated by Django 3.1.5 on 2021-01-31 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='tweet',
            order_with_respect_to='pub',
        ),
    ]
