# Generated by Django 3.1.5 on 2021-01-31 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20210131_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-pub']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='tweet',
            order_with_respect_to=None,
        ),
    ]
