# Generated by Django 3.1.5 on 2021-01-31 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20210131_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-pub', '-hour']},
        ),
    ]
